DROP TABLE IF EXISTS TASK;
DROP SEQUENCE IF EXISTS TASK_SEQUENCE;

CREATE SEQUENCE TASK_SEQUENCE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE TASK(TASK_ID INT PRIMARY KEY, TASK_NAME VARCHAR(255), TASK_DESC VARCHAR(255), TASK_DUE_DATE DATE, TASK_STATUS VARCHAR(255));
